Repository 2020MT93174/DemoProject, pull requests merged in 2021-04, with the labels that each got.

#1 sign-up feature implemented
  src/com/bits/devops/Class1.java
Labels: enhancement

#2 Feature1
  src/com/bits/devops/Class1.java
  src/com/bits/devops/feature1.java
Labels: enhancement

#3 Added Feature 2 File
  src/com/bits/devops/Feature2.java
Labels: feature-added

#4 Feature3
  src/com/bits/devops/Feature1.java
  src/com/bits/devops/Feature3.java
Labels: feature-added

#5 Production
  .project
  src/com/bits/devops/Class1.java
  src/com/bits/devops/Feature2.java
  src/com/bits/devops/feature1.java
Labels: release

#6 Development
  src/com/bits/devops/Feature1.java
  src/com/bits/devops/Feature3.java
Labels: enhancement

#8 Feature1 enhancement
  src/com/bits/devops/Feature1.java
  src/com/bits/devops/feature3.java
Labels: enhancement

#9 Development
  src/com/bits/devops/Feature1.java
  src/com/bits/devops/feature3.java
Labels: enhancement, release

#10 Production
  src/com/bits/devops/Feature1.java
  src/com/bits/devops/feature3.java
Labels: enhancement, release
